name = "almalinux-9"
description = "AlmaLinux 9"
distro = "almalinux-93"
version = "0.0.0"
modules = []
groups = []

[[packages]]
name = "cloud-init"
version = "*"

[[packages]]
name = "firewalld"
version = "*"

[[packages]]
name = "ipa-client"
version = "*"

[[packages]]
name = "subscription-manager"
version = "*"

[customizations.timezone]
timezone = "Europe/Zurich"

[customizations.firewall.services]
enabled = ["cockpit", "ssh"]

[[customizations.files]]
path = "/etc/pki/ca-trust/source/anchors/rabe.ca.crt"
mode = "0644"
user = "root"
group = "root"
data = """
-----BEGIN CERTIFICATE-----
MIIDlTCCAn2gAwIBAgIBATANBgkqhkiG9w0BAQsFADA2MRQwEgYDVQQKDAtJTlQu
UkFCRS5DSDEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTE2MDYy
MzExNTUzOVoXDTM2MDYyMzExNTUzOVowNjEUMBIGA1UECgwLSU5ULlJBQkUuQ0gx
HjAcBgNVBAMMFUNlcnRpZmljYXRlIEF1dGhvcml0eTCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBAMmCtYNSbVHVtmPtq7Ys60NhQd4sMND9uP5IEXlbh2MK
RfQ4G/jUXlFDsWuNpsMMOj7zveXPwVn5JF+j3YjQXWCeDxfqjsTA0fpDIJnMPydZ
HOPFr5MSDb8GhWvgfMP7zw5a34DZwk/UGLGsRs0yMp5xg0MtIrAGQb30fA+Sees3
6J+qDYq3qci6ynWCkrBUiyVtuZaQyjKNbYOiKnVfHwPRCQfUnSjT/GMnKLMaRCNe
1OPh8Rx/1RorQjbiQogUgnl5EY+LiCKnW38nWZAfpkdiq1srocorq1dnR3GOuiS7
nz9p9cQuJPvWBKjSjy+KaRFNaJtx1mOOY11EagluaQsCAwEAAaOBrTCBqjAfBgNV
HSMEGDAWgBQx4/sibdYJdca+q17Q/r02w/uWQTAPBgNVHRMBAf8EBTADAQH/MA4G
A1UdDwEB/wQEAwIBxjAdBgNVHQ4EFgQUMeP7Im3WCXXGvqte0P69NsP7lkEwRwYI
KwYBBQUHAQEEOzA5MDcGCCsGAQUFBzABhitodHRwOi8vaXBhMDEuc2VydmljZS5p
bnQucmFiZS5jaDo4MC9jYS9vY3NwMA0GCSqGSIb3DQEBCwUAA4IBAQCPFi1KGans
7T0U4z/BS97AgiQ1R5qBCVS4XSco7jiLlL3YTl3QQceoZaZuz4P9eizLanukSd0e
82QI2eSW70KEo9cBG96EHq6zAdOkoilKN4AnGCc7yZ/77FaAjwNfyLXtNM0xH3Iu
1UPApiNQGnNcP9+cNRUIwFUM3vWuZEAEkG3L0YNROv5dqXzmyg2RznZ4o+4nkZ0N
ZlAI5dc/YBXor7SjoFtSBs3nib1ikNQ+BoB/I7aNxVxouovwraJMhX0uvQSo3cI9
ZBG9JD+ZEfngycJUtVF9zh1Kn9znIifWQeJOomw5oG451QO6/IxmvoXPlLrde1YH
XeAbl7fsKaCr
-----END CERTIFICATE-----
"""

[[customizations.files]]
path = "/etc/cloud/cloud.cfg"
mode = "0644"
user = "root"
group = "root"
data = """
datasource_list: ["NoCloud", "ConfigDrive"]
"""
