name = "almalinux-9"
description = "AlmaLinux 9"
distro = "almalinux-93"
version = "0.0.0"
modules = []
groups = []

[[packages]]
name = "cloud-init"
version = "*"

[[packages]]
name = "firewalld"
version = "*"

[[packages]]
name = "ipa-client"
version = "*"

[[packages]]
name = "subscription-manager"
version = "*"

[customizations.timezone]
timezone = "Europe/Zurich"

[customizations.firewall.services]
enabled = ["cockpit", "ssh"]

[[customizations.sshkey]]
user = "root"
key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDB1PBMeOamUN3Jo4wyUaNWgkR99T3e9OYdsxnXjuHFZV5igk2Jx6js8pIpOvD6K0tmMiwLVYNNVj+weTtu/5+2s/7pEiXFTyw+ia3A9LerRfBE8ICEbMdeDj8ul9s8IdrvnD9owuwrSw+eMgqK3NTN2q2N77QD80v3sg9Bxg2eNQ+lDpoNOEjZ8kTQcErm+wf2afR1dBIX45T0SpztiWL1DjtmNx1dyA/gkH2A6dkKVHZ/tU5WBXXocqsTRLsVP+MDG7fMurbS9K8cgXsyPWRPhCR3fhWsnSgKVeCuqVpkDW4pNXOxrnD4HNc8KoidIbJXQ6dqNBEJgfQS/JD7zUt4T9/wIXm/IEN3lCaj++kRAewPWEaAoZ504trOaj8UW1EmhjVzc9Q7XMY2J2C2B9Zee5fpT1NMePQcJrIoy9r26Xf1hVR2VFxbktc/rqStg4ZS3CDDQ5SQRMXQeYN1jrRm9iL642+l1y47NoT/mqoWUZvna+0mnwkkBqfEv6e2AYs= operator@server"


[[customizations.files]]
path = "/etc/pki/ca-trust/source/anchors/rabe.ca.crt"
mode = "0644"
user = "root"
group = "root"
data = """
-----BEGIN CERTIFICATE-----
MIIDlTCCAn2gAwIBAgIBATANBgkqhkiG9w0BAQsFADA2MRQwEgYDVQQKDAtJTlQu
UkFCRS5DSDEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTE2MDYy
MzExNTUzOVoXDTM2MDYyMzExNTUzOVowNjEUMBIGA1UECgwLSU5ULlJBQkUuQ0gx
HjAcBgNVBAMMFUNlcnRpZmljYXRlIEF1dGhvcml0eTCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBAMmCtYNSbVHVtmPtq7Ys60NhQd4sMND9uP5IEXlbh2MK
RfQ4G/jUXlFDsWuNpsMMOj7zveXPwVn5JF+j3YjQXWCeDxfqjsTA0fpDIJnMPydZ
HOPFr5MSDb8GhWvgfMP7zw5a34DZwk/UGLGsRs0yMp5xg0MtIrAGQb30fA+Sees3
6J+qDYq3qci6ynWCkrBUiyVtuZaQyjKNbYOiKnVfHwPRCQfUnSjT/GMnKLMaRCNe
1OPh8Rx/1RorQjbiQogUgnl5EY+LiCKnW38nWZAfpkdiq1srocorq1dnR3GOuiS7
nz9p9cQuJPvWBKjSjy+KaRFNaJtx1mOOY11EagluaQsCAwEAAaOBrTCBqjAfBgNV
HSMEGDAWgBQx4/sibdYJdca+q17Q/r02w/uWQTAPBgNVHRMBAf8EBTADAQH/MA4G
A1UdDwEB/wQEAwIBxjAdBgNVHQ4EFgQUMeP7Im3WCXXGvqte0P69NsP7lkEwRwYI
KwYBBQUHAQEEOzA5MDcGCCsGAQUFBzABhitodHRwOi8vaXBhMDEuc2VydmljZS5p
bnQucmFiZS5jaDo4MC9jYS9vY3NwMA0GCSqGSIb3DQEBCwUAA4IBAQCPFi1KGans
7T0U4z/BS97AgiQ1R5qBCVS4XSco7jiLlL3YTl3QQceoZaZuz4P9eizLanukSd0e
82QI2eSW70KEo9cBG96EHq6zAdOkoilKN4AnGCc7yZ/77FaAjwNfyLXtNM0xH3Iu
1UPApiNQGnNcP9+cNRUIwFUM3vWuZEAEkG3L0YNROv5dqXzmyg2RznZ4o+4nkZ0N
ZlAI5dc/YBXor7SjoFtSBs3nib1ikNQ+BoB/I7aNxVxouovwraJMhX0uvQSo3cI9
ZBG9JD+ZEfngycJUtVF9zh1Kn9znIifWQeJOomw5oG451QO6/IxmvoXPlLrde1YH
XeAbl7fsKaCr
-----END CERTIFICATE-----
"""

[[customizations.files]]
path = "/etc/cloud/cloud.cfg"
mode = "0644"
user = "root"
group = "root"
data = """
datasource_list: ["NoCloud", "ConfigDrive"]
"""
