name = "almalinux-9"
description = "AlmaLinux 9"
distro = "almalinux-91"
version = "0.0.0"
modules = []
groups = []

[[packages]]
name = "cloud-init"
version = "*"

[[packages]]
name = "firewalld"
version = "*"

[[packages]]
name = "ipa-client"
version = "*"

[[packages]]
name = "subscription-manager"
version = "*"

[[packages]]
name = "vim"
version = "*"

[[packages]]
name = "podman"
version = "*"

[[containers]]
source = "ghcr.io/radiorabe/ubi9-minimal:0.2.0"

[customizations]

[customizations.timezone]
timezone = "Europe/Zurich"

[customizations.firewall.services]
enabled = ["cockpit", "ssh"]

[customizations.services]
enabled = ["sshd", "cockpit.socket"]

[[customizations.sshkey]]
user = "root"
key = "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvv0JHfOaqUR0XShL66xUw5lWQQSwoo8IdRigObgcPrWKc8BrYDjQmWGuyLG/Y14v0XLZ/xv6qyX6yRVLWJNm2PsO7g739KZWvIC49kMhfqjEm7hr2NHaQVNuAJlavE7JLt9WjRPY5GvTYAjnBB49rTATT+wPshNMlnI/cnf21Cn+0kbltB6q8lIeo/gDW8XYsTCPKvikSPAAFgUozljnwW7DNeFlag8e8pPAB1VFJOafwJPZ++jyUPFd0+gCOCk7pvfOlVST/r6Iplyw4K5KkcWhxWMCz5MvYkC9jUSmGjpfaQvbExordbeNr+zkvTGsj8XWVLWV0KK0LwBvVBDFOQ=="

[[customizations.user]]
name = "admin"
description = "Local Admin User"
password = "$6$t58wJBNUgBnRbPcz$OiTh3obvlTx4/bNyiYrItckqFMMEyrM88o.KjHqdWDK2lB3egQUguvVjIG6mbVSMqetumC8NXNGU..3tVTUfP/"
key = "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvv0JHfOaqUR0XShL66xUw5lWQQSwoo8IdRigObgcPrWKc8BrYDjQmWGuyLG/Y14v0XLZ/xv6qyX6yRVLWJNm2PsO7g739KZWvIC49kMhfqjEm7hr2NHaQVNuAJlavE7JLt9WjRPY5GvTYAjnBB49rTATT+wPshNMlnI/cnf21Cn+0kbltB6q8lIeo/gDW8XYsTCPKvikSPAAFgUozljnwW7DNeFlag8e8pPAB1VFJOafwJPZ++jyUPFd0+gCOCk7pvfOlVST/r6Iplyw4K5KkcWhxWMCz5MvYkC9jUSmGjpfaQvbExordbeNr+zkvTGsj8XWVLWV0KK0LwBvVBDFOQ=="
home = "/home/admin/"
shell = "/usr/bin/bash"
groups = ["users", "wheel"]
uid = 1000

[customizations.openscap]
datastream = "/usr/share/xml/scap/ssg/content/ssg-almalinux9-ds.xml"
profile_id = "xccdf_org.ssgproject.content_profile_cis"
tailoring = "/etc/osbuild-comsposer/oscap/xccdf_ch.hairmare.content_profile_cis_light.xml"
